name: 'Tests'
on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
  push:
    branches-ignore:
      - 'gh-pages'
  workflow_dispatch:
    branches-ignore:
      - 'gh-pages'
    inputs:
      deploy:
        description: 'Deploy: [true, false]'
        required: true
        default: 'false'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Install dependencies
      run: yarn install
    #- name: Run linters(ignore errors for now)
      #run: yarn lint || true
    - name: Run jest tests
      run: yarn test
