name: 'Tests'
on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
  push:
    branches-ignore:
      - 'gh-pages'
  workflow_dispatch:
    branches-ignore:
      - 'gh-pages'
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Install dependencies
      run: yarn install

    - name: Run jest tests
      run: yarn test

    - name: Run integration tests
      env:
        API_KEY: ${{ secrets.TEST_API_KEY }}
        API_URL: ${{ secrets.TEST_API_URL }}
      run: yarn integration

    - name: Run production build to ensure the build works
      run: yarn build
